FinalCineast/Cineast_final_web/Cineast_final_web/src/managedBeans_Controllers/EditorBean.java
package managedBeans_Controllers;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import edu.esprit.pfa.cineast.entities.Forum;
import edu.esprit.pfa.cineast.services.imp.ForumDAOLocal;

@ManagedBean(name="editorBean")
@ViewScoped
public class EditorBean {
	
	@EJB
	private ForumDAOLocal forumEjb;
	
	private List<Forum> forums;
	  
    private String value; 
    
   @PostConstruct
   public void init(){
	   setForums(forumEjb.retrieveAll());
   }
  
   //******* getters and setters ***********/
	public String getValue() {  
        return value;  
    }  
  
    public void setValue(String value) {  
        this.value = value;  
    }

	public List<Forum> getForums() {
		return forums;
	}

	public void setForums(List<Forum> forums) {
		this.forums = forums;
	}  
    
    
}  

FinalCineast/src/managedBeans_Controllers/EditorBean.java
package managedBeans_Controllers;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import edu.esprit.pfa.cineast.entities.Forum;
import edu.esprit.pfa.cineast.services.imp.ForumDAOLocal;

@ManagedBean(name="editorBean")
@ViewScoped
public class EditorBean {
	
	@EJB
	private ForumDAOLocal forumEjb;
	
	private List<Forum> forums;
	  
    private String value; 
    
   @PostConstruct
   public void init(){
	   setForums(forumEjb.retrieveAll());
   }
  
   //******* getters and setters ***********/
	public String getValue() {  
        return value;  
    }  
  
    public void setValue(String value) {  
        this.value = value;  
    }

	public List<Forum> getForums() {
		return forums;
	}

	public void setForums(List<Forum> forums) {
		this.forums = forums;
	}  
    
    
}  

FinalCineast/src/managedBeans_Controllers/LanguageBean.java
package managedBeans_Controllers;



import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
 
@ManagedBean(name="language")
@SessionScoped
public class LanguageBean implements Serializable{
	
	private static final long serialVersionUID = 1L;
	
	private String localeCode;
	
	private static Map<String,Object> countries;
	static{
		countries = new LinkedHashMap<String,Object>();
		countries.put("English", Locale.ENGLISH); //label, value
		countries.put("French", Locale.FRANCE);
	}

	public Map<String, Object> getCountriesInMap() {
		return countries;
	}

	
	public String getLocaleCode() {
		return localeCode;
	}


	public void setLocaleCode(String localeCode) {
		this.localeCode = localeCode;
	}


	public void countryLocaleCodeChanged(ValueChangeEvent e){
		
		String newLocaleValue = e.getNewValue().toString();
		
		//loop a map to compare the locale code
        for (Map.Entry<String, Object> entry : countries.entrySet()) {
        
        	if(entry.getValue().toString().equals(newLocaleValue)){
        		
        		FacesContext.getCurrentInstance()
        			.getViewRoot().setLocale((Locale)entry.getValue());
        		
        	}
        }

	}


}

FinalCineast/WebContent/pages/chatroom.xhtml

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.prime.com.tr/ui">
    <h:head>
        <title>Chat Room</title>
        <script type="text/javascript">
            var jq = jQuery;
                        function handlePublish(pushed){

         

                 var msg = decodeURIComponent(pushed.data); 

                  msg = msg.replace(/\+/g, " "); 

                 jq("#outPanel_content").append(msg+"<br/>");
                
            }
        </script>
    </h:head>
    <h:body>
        <h:form prependId="false">
            <h:inputText value="#{chatBean.message}"/>
            <p:commandButton value="Send" actionListener="#{ChatBean.send}"/>
        </h:form>
        <p:panel id="outPanel"/>
        <p:push channel="chat" onpublish="handlePublish"/>
    </h:body>
</html>

FinalCineast/WebContent/pages/contact.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="/template/template.xhtml">

	<ui:define name="mainContent">
		<h:form>
		
		<div class="main">
 	<div class="wrap">
        <div class="content">
     	<div class="content_top">
    		<div class="back-links">
    		<p><a href="index.xhtml">Home</a> &gt;&gt;&gt;&gt; <a href="contact.xhtml" class="active">Contact</a></p>
    	    </div>
    		<div class="clear"></div>
    	</div>
    	
    	<div class="section group">
				<div class="col span_2_of_3">
				  <div class="contact-form">
				  	<h2>Contact Us</h2>
					    <h:form >
					    	<div>
						    	<span><label>E-mail</label></span>
						    	<span><h:inputText value="#{ContactController.from}" name="userEmail"  /> </span>
						    </div>
						    <div>
						    	<span><label>Password</label></span>
						    	<span><h:inputSecret  value="#{ContactController.password}"  name="userPwd" style="
    padding: 8px;   display: block;   width:98%;   background:none;   border:1px solid #CACACA;   outline: none;   color: #464646;   font-size:1em;   font-weight:bold;   font-family: Arial, Helvetica, sans-serif;   -webkit-appearance: none;
"/> </span>
						    </div>
						    <div>
						     	<span><label>Company Name</label></span>
						    	<span><h:inputText value="#{ContactController.too}" name="userPhone"/></span>
						    </div>
						    <div>
						    	<span><label>Subject</label></span>
						    	<span><h:inputTextarea name="userMsg" value="#{ContactController.mesg}"> </h:inputTextarea></span>
						    </div>
						   <div>
						   		<span><h:commandButton  value="SEND" action="#{ContactController.sendMail()}" type="submit" /></span>
						  </div>
					    </h:form>
				  </div>
  				</div>
				<div class="col span_1_of_3">
					<div class="contact_info">
    	 				<h2>Find Us Here</h2>
					    	  <div class="map">
							   	    <img src="/template/esprit.JPG" width="100" height="175"/> <br/><small><a href="https://maps.google.co.in/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Lighthouse+Point,+FL,+United+States&amp;aq=4&amp;oq=light&amp;sll=26.275636,-80.087265&amp;sspn=0.04941,0.104628&amp;ie=UTF8&amp;hq=&amp;hnear=Lighthouse+Point,+Broward,+Florida,+United+States&amp;t=m&amp;z=14&amp;ll=26.275636,-80.087265" style="color:#888;text-align:left;font-size:0.85em">View Larger Map</a></small>
							  </div>
      				</div>
      			<div class="company_address">
				     	<h2>Information :</h2>
						    	<p>ESPRIT, EL-GHAZALA</p>
						   		<p>TUNISIE</p>
						   	
				   		<p>Phone:+216 70 685 685</p>
				   		
				 	 	<p> Site : <span><a href="#">esprit.ens.tn</a></span></p>
				   		<p>Follow on: <span><h:commandLink value="" action="https://www.facebook.com/cineast4info1" >Facebook</h:commandLink></span>, <span><a href="#">Twitter</a></span></p>
				   </div>
				 </div>
			  </div>		
         </div> 

</div></div>
			
    
		</h:form>
	</ui:define>

</ui:composition>

</html>

FinalCineast/WebContent/pages/editor.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">


<ui:composition template="/template/template.xhtml">

	<ui:define name="mainContent">
		<h:form>

<div class="main">

<div>

<h:form>  
  
    <p:growl id="growl" showDetail="true"/>  
  
    <p:dataTable value="#{editorBean.forums}" var="f">
    
    <p:panel header="Cineast Forum" footer="Cineast!">  
        <p:column><p:outputLabel value="#{f.registredUser.surname}"></p:outputLabel>
     </p:column>
     <br/>
     <p:column>
        <h:outputText value="#{f.comment}" />  
        </p:column>
    </p:panel>  
    </p:dataTable>
</h:form>
</div>


<div>

<h:form id="form">  

  
    <p:editor id="editor" value="#{editorbeancreat.val}" width="1343"/> 
 
    <h:panelGrid columns="2" style="margin-top:10px">  
        <p:commandButton id="submitButton" value="Submit" update="display" oncomplete="dlg.show()"  
                        icon="ui-icon-disk" action="#{editorbeancreat.doAddcomment()}" />  
        <p:commandButton id="clearButton" type="button" value="Clear" onclick="PF('editor').clear()"  
                        icon="ui-icon-close" />  
    </h:panelGrid>  
  
    <p:dialog header="Content" widgetVar="dlg" showEffect="fade" hideEffect="fade" modal="true">  
        <h:outputText id="display" value="#{editorbeancreat.forum.comment}" escape="false" />  
    </p:dialog>  
  
</h:form>  
</div>

</div>

</h:form>
	</ui:define>

</ui:composition>

 
</html>

FinalCineast/WebContent/pages/index.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="/template/template.xhtml">

	<ui:define name="mainContent">
		<h:form>

        

            








			
    
		</h:form>
	</ui:define>

</ui:composition>

</html>

FinalCineast/WebContent/pages/manageaccount.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="/template/template.xhtml">

	<ui:define name="mainContent">
		
		
	   <h:form style="margin-left:3cm" >
	   <br/>
	   <br/>
	   <p:graphicImage value="#{manuser.reguser.pic}"></p:graphicImage>
	   <p:fileUpload value="#{manuser.reguser.pic}"></p:fileUpload>
	   <br/>
	   <br/>
	   <h4>user name</h4>
	   <p:inputText  value="#{manuser.reguser.login}"  />
	   <br/>
	   <br/>
	   <h4>Last Name</h4>
	   <p:inputText  value="#{manuser.reguser.surname}" />
	   <br/>
	   <br/>
	   <h4>First Name</h4>
	   <p:inputText value="#{manuser.reguser.name}" />
	   <br/>
	   <br/>
	   <h4>Birth date</h4>
	      <p:growl id="growl" showDetail="true"/>
<p:calendar pattern=" dd/MM/yyyy" showButtonPanel="true" navigator="true" id="customCal" value="#{manuser.reguser.birthday}"></p:calendar>
	   <br/>
	   <br/>
	   <h4>nationality</h4>
	       <p:selectOneListbox id="basic" value="#{manuser.reguser.nationality}">
            <f:selectItem itemLabel="Tunisia" itemValue="Tunisia" />
            <f:selectItem itemLabel="America" itemValue="America" />
            <f:selectItem itemLabel="France" itemValue="France" />
             <f:selectItem itemLabel="Japan" itemValue="Japan" />
            <f:selectItem itemLabel="Algeria" itemValue="Algeria" />
            <f:selectItem itemLabel="Marocco" itemValue="Marocco" />
        </p:selectOneListbox>
        
	   <br/>
	    <br/>
	    <h4>Phone number</h4>
	    <p:inputText value="#{manuser.reguser.telephonNumber}" />
	   <br/>
	   <br/>
	   <h4>CIN</h4>
	   <p:inputText value="#{manuser.reguser.CIN}" />
	   <br/>
	   <br/>
	   <h4>do you want to change your password </h4>
	   <h:inputSecret  value="#{manuser.reguser.password}" />
	   <h5>confirm</h5>
	   <h:inputSecret value="#{manuser.reguser.password}" /> 
	   <br/>
	   <br/>
	   <h4>you have a new E-mail</h4>
	   <p:inputText  value="#{manuser.reguser.email}" />
	   <h5>confirm</h5>
	   <p:inputText  value="#{manuser.reguser.email}"   />
	   <br/>
	   <br/>
	   
	   
	   <p:commandButton value="save changes" action="#{manuser.doSaveChanges()}" />
	   <p:commandButton  value="Delete Profil" />
	   
	   </h:form>
	</ui:define>

</ui:composition>

</html>

FinalCineast/WebContent/pages/previewandcomment.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="/template/template.xhtml">

	<ui:define name="mainContent">
		<h:form>
<p:media style="margin-left: 7cm" value="http://www.youtube.com/v/PAQGkn_nsrE" width="600" height="500" player="flash"/> 
<p:dataTable value="#{commbean.comments}" var="c">
<p:column width="200">
<f:facet name="user">
</f:facet>
<p:graphicImage value="#{c.owner.pic}"></p:graphicImage>
<p:outputLabel value="#{c.owner.name}"></p:outputLabel>
</p:column><p:column>
<p:outputLabel value="#{c.text}"></p:outputLabel>
</p:column>

</p:dataTable>
<h:form>
<h2>your comments here </h2>
<p:inputTextarea  name ="comment" autoResize="true" style="margin-left: 3cm" rows="4" cols="50" completeMethod="#{autoCompleteBean.completeArea}" queryDelay="750" minQueryLength="4" value="#{commentbeans.comm.text}"  />
      
                    
  <h:commandButton value="post" action="#{commentbeans.doAddcomment()}" />     
               
  </h:form>
  </h:form>
	</ui:define>

</ui:composition>

</html>

FinalCineast/WebContent/pages/showaccount.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="/template/template.xhtml">

	<ui:define name="mainContent">
		<h:form>
		
	<h:dataTable columns="2" value="#{manuser.reguser}" var="us">
	<h:column>
	<h:outputText value="#{us.email}" />
	</h:column>
	
	<h:column>
	<h:outputText value="#{us.login}" />
	</h:column>
	
	<h:column>
	<h:outputText value="#{us.login}" />
	</h:column>
	
	</h:dataTable>
	
	<br/>
	<h:commandButton value="Manage Your Account" action="manageaccount?faces-redirect=true" />
			
    
		</h:form>
	</ui:define>

</ui:composition>

</html>

FinalCineast/WebContent/pages/useregister.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">


<ui:composition template="/template/template.xhtml">

	<ui:define name="mainContent">
		<h:form>
		

<div class="container">
		<div class="row">
			<div class="col-md-4 col-md-offset-4">
				<div class="login-panel panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">Registration Form</h3>
					</div>
							<h:form>
			
			<h3>
				<h:outputText value="#{msg['welcome.jsf']}" />
			</h3>
			
			<h:panelGrid columns="2">
				
				Language : 
				<h:selectOneMenu value="#{language.localeCode}" onchange="submit()"
					valueChangeListener="#{language.countryLocaleCodeChanged}">
   					<f:selectItems value="#{language.countriesInMap}" /> 
   				</h:selectOneMenu>

			</h:panelGrid>
			
			
			
		</h:form>
					<h:form id="registrationForm">
						<div class="panel-body">
							<fieldset>
								<div class="form-group">
									<h:outputText value=" Name" />
									<h:message for="firstNameField" styleClass="form-error" />
									<h:inputText id="firstNameField" class="form-control"
										required="true" requiredMessage=" is mendatory"
										validatorMessage=" is an alphabetical field"
										value="#{userController.user.name}">
										<f:validateRegex pattern="[a-z A-Z]*" for="firstNameField" />
									</h:inputText>
								</div>
<!-- 								<div class="form-group"> -->
<!-- 									<h:outputText value="Birthdate" /> -->
<!-- 									<h:message for="BirthdateField" styleClass="form-error" /> -->
<!-- 									<h:inputText id="BirthdateField" class="form-control" -->
<!-- 										required="true" requiredMessage=" is mendatory" -->
<!-- 										validatorMessage=" is alphabetical field" -->
<!-- 										value="#{userController.user.birthday}"> -->
<!-- 										<f:validateRegex pattern="[a-z A-Z]*" for="BirthdateField" /> -->
<!-- 									</h:inputText> -->
<!-- 								</div> -->

								<div class="form-group">
									<h:outputText value="Gender" />
									<h:selectOneMenu class="form-control"
										value="#{userController.user.sexe}">
										<f:selectItem itemLabel="Female" itemValue="false" />
										<f:selectItem itemLabel="Male" itemValue="true" />
									</h:selectOneMenu>
								</div>

								<div class="form-group">
									<h:outputText value="E-mail" />
									<h:message for="eMailField" styleClass="form-error" />
									<h:inputText id="eMailField" class="form-control"
										required="false" requiredMessage=" is mendatory"
										validatorMessage=" must be well formed"
										value="#{userController.user.email}">
										<f:validateRegex
											pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$"
											for="eMailField" />
									</h:inputText>
								</div>
								<div class="form-group">
									<h:outputText value="Password" />
									<h:message for="passwordField" styleClass="form-error" />
									<h:inputSecret id="passwordField" redisplay="true" class="form-control"
										required="true" requiredMessage=" is mendatory"
										validatorMessage=" length must be between 8 and 12 characters"
										value="#{userController.user.password}">
										<f:validateLength minimum="8" maximum="12" for="passwordField" />
									</h:inputSecret>
								</div>
								<h:commandButton class="btn btn-lg btn-success btn-block"
									value="Register" type="submit"
									action="#{userController.doRegisterTeacher()}" />
							</fieldset>
						</div>
					</h:form>
				</div>
			</div>
		</div>
	</div>
	
			
    
		</h:form>
	</ui:define>

</ui:composition>

</html>